### ISSUE TITLE
无法新建

### ISSUE THREAD

**Issue by hqzh** [jurieo/chatgpt-share-web#1]
![image](https://github.com/jurieo/chatgpt-share-web/assets/26128706/bd792424-fe2d-41d7-841c-0c9d1e149c20)

**Comment by jurieo** [comment]
这是因为点击新增的时候浏览器没有过人机验证。当出现下面这个提示，就可以正常录入账号密码了。如果没有出现刷新网页即可。
现在全网大多数镜像网站都不可用，xyhelper在紧急修复，修复完成，就可以正常录入了，稍等片刻。
<img width="610" alt="WechatIMG290" src="https://github.com/jurieo/chatgpt-share-web/assets/18009286/de5ffd9d-c420-4fde-aaae-330ea89e63c7">

**Comment by hqzh** [comment]
@jurieo 蟑螂修复了，大佬还没同步吗
