### ISSUE TITLE
公告没有生效

### ISSUE THREAD

**Issue by hqzh** [jurieo/chatgpt-share-web#2]
![image](https://github.com/jurieo/chatgpt-share-web/assets/26128706/ac802b1f-7c6d-4cd5-967a-bcbfd6beb792)

**Comment by hqzh** [comment]
![image](https://github.com/jurieo/chatgpt-share-web/assets/26128706/d1ed86ca-df80-4be8-b008-750fce22107c)

**Comment by jurieo** [comment]
> ![image](https://private-user-images.githubusercontent.com/26128706/316503872-ac802b1f-7c6d-4cd5-967a-bcbfd6beb792.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzY3MTgsIm5iZiI6MTcxMTM3NjQxOCwicGF0aCI6Ii8yNjEyODcwNi8zMTY1MDM4NzItYWM4MDJiMWYtN2M2ZC00Y2Q1LTk2N2EtYmNiZmQ2YmViNzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0MjAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNDg3ZjUyMGViZjk1MjA1MTRmMDBjNjY1YzZlMDU3MGU3NjZmZGJjMWM2NzBiODQ4ZTliMGJhNmNlMjNjYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j9BqgEkUaphWw5QiDRh-iRswzEkmVS8VQ2yjit_WqoU)

你把图截全一点吧
<img width="797" alt="image" src="https://github.com/jurieo/chatgpt-share-web/assets/18009286/2738c8d3-1dc4-469e-8dcb-59f5b6ea2585">

**Comment by hqzh** [comment]
notice手抖拼错了
